### ISSUE TITLE
Run-on sentence

### ISSUE THREAD

**Issue by MarceloDamian** [hunter-college-ossd-spr-2020/chislee0708-weekly#4]
You could split up " For example, Auth0 Lock Passwordless created by Auth0 is a FOSS project under the MIT license that I recently found on Github, it allows users to log in to certain application by receiving a one-time password via email or text message. " into 2 sentences. The first being "For example, Auth0 Lock Passwordless created by Auth0 is a FOSS project under the MIT license that I recently found on Github." The second one being "Auth0 Lock Passwordless allows users to log in to certain applications by receiving a one-time password via email or text message."

**Comment by chislee0708** [comment]
Thanks for the advice!
